#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BIOMETRICS_AGENT_TIMEOUT_DEFAULT_SECONDS="${BIOMETRICS_AGENT_TIMEOUT_DEFAULT_SECONDS:-120}"
BIOMETRICS_AGENT_TIMEOUT_CODER_SECONDS="${BIOMETRICS_AGENT_TIMEOUT_CODER_SECONDS:-600}"
BIOMETRICS_AGENT_TIMEOUT_FIXER_SECONDS="${BIOMETRICS_AGENT_TIMEOUT_FIXER_SECONDS:-600}"

echo "[soak-72h] agent timeouts: default=${BIOMETRICS_AGENT_TIMEOUT_DEFAULT_SECONDS}s coder=${BIOMETRICS_AGENT_TIMEOUT_CODER_SECONDS}s fixer=${BIOMETRICS_AGENT_TIMEOUT_FIXER_SECONDS}s"

DURATION_HOURS="72" \
GOAL_PARTS="50" \
SCHEDULER_MODE="dag_parallel_v1" \
MAX_PARALLELISM="8" \
PROFILE_LABEL="ga-72h" \
RUN_INTERVAL_SECONDS="15" \
POLL_INTERVAL_SECONDS="2" \
RUN_TIMEOUT_SECONDS="1800" \
FAIL_ON_GATES="true" \
BIOMETRICS_AGENT_TIMEOUT_DEFAULT_SECONDS="${BIOMETRICS_AGENT_TIMEOUT_DEFAULT_SECONDS}" \
BIOMETRICS_AGENT_TIMEOUT_CODER_SECONDS="${BIOMETRICS_AGENT_TIMEOUT_CODER_SECONDS}" \
BIOMETRICS_AGENT_TIMEOUT_FIXER_SECONDS="${BIOMETRICS_AGENT_TIMEOUT_FIXER_SECONDS}" \
"${ROOT_DIR}/scripts/release/run-soak-rehearsal.sh" --hours 72 --profile-label ga-72h "$@"
